export const STUDENT_ACTIONS = {
  SET_STUDENTS: 'SET_STUDENTS',
  ADD_STUDENT: 'ADD_STUDENT',
  UPDATE_ATTENDANCE: 'UPDATE_ATTENDANCE',
  DELETE_STUDENT: 'DELETE_STUDENT',
  RESET: 'RESET',
};


export default STUDENT_ACTIONS;
